title: Annie's Blog
author: Annie Rosen
email: annarosen16@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  writing a description here. 

# social links
#twitter_username: your-twitter-handle
#github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
